swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/profile:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /accounts:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Get a list of user accounts
      description: Returns all accounts belonging to the authenticated user
      produces:
        - application/json
      responses:
        "200":
          description: Accounts successfully retrieved
          schema:
            $ref: "#/definitions/Accounts"
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
  /accounts/{accountId}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Get a list of transactions for account
      description: Returns all transactions for a specific account
      parameters:
        - in: path
          name: accountId
          type: string
          description: Account ID
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: Transactions successfully retrieved
          schema:
            $ref: "#/definitions/Transactions"
        "401":
          description: Unauthorized
        "404":
          description: Returns an error - No element found
        "500":
          description: Internal Server Error
  /transactions/{transactionsId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Get transaction elements
      description: Fetch elements of specific transaction
      parameters:
        - in: path
          name: transactionsId
          description: ID of the transaction
          required: true
          type: string
      responses:
        "200":
          description: Transaction elements retrieved successfully
          schema:
            $ref: "#/definitions/TransactionElements"
        "401":
          description: Unauthorized
        "404":
          description: Transactions not found
        "500":
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  Accounts:
    type: object
    properties:
      status:
        type: integer
        description: Status code
      message:
        type: string
        description: Response message
      body:
        type: array
        items:
          type: object
          properties:
            accountId:
              type: string
              description: Account ID
            nameAccount:
              type: string
              description: Account title
            amountBalance:
              type: number
              description: Account balance
            etatBalance:
              type: string
              description: Balance status
  Transactions:
    type: object
    properties:
      status:
        type: integer
        description: Status code
      message:
        type: string
        description: Response message
      body:
        type: array
        items:
          type: object
          properties:
            transactionId:
              type: string
              description: Transaction ID
            Date:
              type: string
              format: date
              description: Date of transaction
            desciption:
              type: string
              description: description Transactions
            amount:
              type: number
              description: value transactions
            balanceValue:
              type: number
              description: value of balance
  TransactionElements:
    type: object
    properties:
      status:
        type: integer
        description: Status code
      message:
        type: string
        description: Response message
      body:
        type: array
        items:
          type: object
          properties:
            transactionId:
              type: string
              description: Transaction ID
            Date:
              type: string
              format: date
              description: Date of transaction
            desciption:
              type: string
              description: Description Transactions
            amount:
              type: number
              description: Value transactions
            balanceValue:
              type: number
              description: Value of balance
            transactionType:
              type: string
              description: Type of transaction
            category:
              type: string
              description: Category of transaction
            note:
              type: string
              description: To enter a comment
